version: '3'
services:
  db:
    image: postgres:10.4
    ports:
<<<<<<< HEAD
    - 5432
=======
      - 5432:5432
>>>>>>> 87b08b403c10335eb333ce2b9d1d579d9aa7837d
    environment:
    - POSTGRES_DB=zeit_tasting_lab_production
    - POSTGRES_USER=zeit_tasting_lab
    - POSTGRES_PASSWORD=jdking666
    volumes:
    - "./data:/var/lib/postgresql/data"
    networks:
    - back

  web:
    restart: always
    build: .
    volumes:
      - ~/storage/zeit-tasting-lab:/home/app/storage
    depends_on:
    - db
    ports:
<<<<<<< HEAD
    - 80
    links:
    - db
    environment:
    - RAILS_MASTER_KEY=aa86589e0f390ab08513e273f06b2cae
    - VIRTUAL_HOST=tastinglab.co
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=tastinglab.co
    - LETSENCRYPT_EMAIL=info@tastinglab.co
    networks:
    - front
    - back
=======
      - 80:80
    links:
      - db
    environment:
      - RAILS_ENV=production
>>>>>>> 87b08b403c10335eb333ce2b9d1d579d9aa7837d

networks:
  front:
    external:
      name: zeitxlinck_front
  back:
