version: '3'
services:
  web:
    restart: always
    build: .
    ports:
    - "80:80"
#    environment:
#    - VIRTUAL_HOST=tastinglab.co
#    - VIRTUAL_PORT=80
#    - LETSENCRYPT_HOST=tastinglab.co
#    - LETSENCRYPT_EMAIL=info@tastinglab.co
      # volumes:
      #- ./log:/app/log
      #- ./public/assets:/app/public/assets
