version: '3'
services:
  db:
    image: postgres:10.4
    ports:
    - 5432
    environment:
    - POSTGRES_DB=zeit_tasting_lab_production
    - POSTGRES_USER=zeit_tasting_lab
    - POSTGRES_PASSWORD=jdking666
    volumes:
    - "./data:/var/lib/postgresql/data"
    networks:
    - back

  web:
    restart: always
    build: .
    depends_on:
    - db
    ports:
    - 80
    links:
    - db
    environment:
    - RAILS_MASTER_KEY=aa86589e0f390ab08513e273f06b2cae
    - VIRTUAL_HOST=tastinglab.co
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=tastinglab.co
    - LETSENCRYPT_EMAIL=info@tastinglab.co
    networks:
    - front
    - back

networks:
  front:
    external:
      name: zeitxlinck_front
  back:
