default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: root
  password: iii@root
  database: zeit_tasting_lab_development

test:
  <<: *default
  database: zeit_tasting_lab_test

production:
  <<: *default
  database: zeit_tasting_lab_production
  username: zeit_tasting_lab
  password: <%= ENV['ZEIT_TASTING_LAB_DATABASE_PASSWORD'] %>
